/* ==========================================================
 * 合戦ズ ― maps.js（マップデータ）
 * 各マップのタイル行列と MAP_DEFS（通行判定・NPC・アクション・エンカウント）、
 * HD-2D の装飾・建物の配置データ、リニモ（駅・高架軌道）の定義をまとめたデータ専用ファイル。
 * dialogue.js と同じく、index.html で game.js より先に読み込む。
 * 行はすべて同じ幅（屋外40 / 屋内16）であること。
 *
 * 街の配置は実際の長久手市に準拠（方角込み）。zoneA は現地案内図に合わせ、
 * 画面上=芸大通、下=杁ヶ池公園、左=市役所方面として描く。古戦場駅付近では
 * リニモが画面を縦に走り、イオン（上）と記念館（下）の間を東西道路が通る。
 * ========================================================== */

const MUSEUM = [
  '################',
  '#..B...B...B...#',
  '#..............#',
  '#....K....S....#',
  '#..............#',
  '#..............#',
  '#......@.......#',
  '#..............#',
  '#..............#',
  '#..............#',
  '#..............#',
  '#..............#',
  '#..............#',
  '#######DD#######',
];
const FIELD = [
  'TTTTTTTTTTTTTTTT',
  'T..............T',
  'T...T....T.....T',
  'T..............T',
  'T......i.......T',
  'T.....,,,......T',
  'T....,,m,,.....T',
  'T....,,,,,.....T',
  'T~~..,,,,,..~~~T',
  'T~~..,,,,,..~~~T',
  'T....,,,,,.....T',
  'T......@P......T',
  'T.....M........T',
  'TTTTTTTTTTTTTTTT',
];
// ゾーンA: 長久手古戦場駅周辺（画面上=芸大通・下=杁ヶ池公園・左=市役所方面）
// W/^=記念館, D=記念館入口, M=勝入塚, N=庄九郎塚, R=岩, b=茂み, P=セーブ篝火,
// I/4=イオン, a=血の池公園, e=リニモ長久手古戦場駅, r=道路（横9-10・縦35-37）
const ZONEA = [
  'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTrrrTT',
  'T..................................rrr.T',
  'T...IIIIIII........................rrr.T',
  'T.T.IIIIIII....T...................rrr.T',
  'T...IIIIIII................T.......rrr.T',
  'T...IIIIIII........................rrr.T',
  'T...II444II.....................eeerrr.T',
  'T...............................eeerrr.T',
  'T...............................eeerrr.T',
  'rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrT',
  'rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrT',
  'T................,,,...............rrr.T',
  'T................,,,...............rrr.T',
  'T................,,,...............rrr.T',
  'T.~~~.......^^^^^^^^^^^^^..........rrr.T',
  'T.~~~.......WWWWWWWWWWWWW..........rrr.T',
  'T.~~~.......WWWWWWWWWWWWW..........rrr.T',
  'T...........WWWWWWWWWWWWW..........rrr.T',
  'T...........WWWWWWWWWWWWW..........rrr.T',
  'T.T.........WWDDDDDDDDDWW..........rrr.T',
  'T....bbb....................M......rrr.T',
  'T....bbb...........................rrr.T',
  'T....bbbR.....................N....rrr.T',
  'T..bbb.............................rrr.T',
  'T..bab..........................T..rrr.T',
  'T..bbb.............@.......P.......rrr.T',
  'T..................................rrr.T',
  'T..................................rrr.T',
  'T..................................rrr.T',
  'T..................................rrr.T',
  'T..................................rrr.T',
  'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTrrrTT',
];
// ゾーンB: 西エリア（杁ヶ池公園・杁ヶ池公園駅・御旗山・はなみずき通の住宅地）
// ~=杁ヶ池, a=公園の看板, N=御旗山, e=杁ヶ池公園駅, W/^=住宅
const ZONEB = [
  'TTTTTTTTTTTTTTTTTTT...TTTTTTTTTTTTTTTTTT',
  'T......................................T',
  'T.....T..T....................T........T',
  'T.T.......T................T.....T.....T',
  'T...~~~~~~.............................T',
  'T...~~~~~~....................N........T',
  'T...~~~~~~................T.......T....T',
  'T..T~~~~~~.T...........................T',
  'T...~~~~~~..................T...T......T',
  'T.T........T...........................T',
  'T....b.a.b.............................T',
  'T......................................T',
  'T......................................T',
  'T......................................T',
  'T......................................T',
  'T......................................T',
  'T......................................T',
  'T......................................T',
  'T.........eee..........................T',
  'T.........eee..........................T',
  'T.......................................',
  'Trrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr',
  'Trrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr',
  'T.......................................',
  'T.....^^^^......T.........^^^^.........T',
  'T.....WWWW....T......T....WWWW...T.....T',
  'T.....WWWW................WWWW.........T',
  'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
];
// ゾーンC: 岩作（色金山＋床机石・茶室・安昌寺・市役所・愛知医大病院・武蔵塚・一蘭）
// J=岩山/寺, R=床机石, 1=茶室, 2=市役所, h=医大病院, Y/4=一蘭, M=武蔵塚, x=射的, r=県道57号
const ZONEC = [
  'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
  'T...................................rrrT',
  'T.T..........JJJJJJJJJ.......^^^^^^^rrrT',
  'T.........T..JJJJJJJJJ...T...^^^^^^^rrrT',
  'T...JJJJJ....JJJJRJJJJ.......WWWWWWWrrrT',
  'T...JJJJJ....JJJJ,JJJJ.......WWWhWWWrrrT',
  'T...JJJJJ....JJJJ,JJJJ..............rrrT',
  'T.....o......JJJJ,JJJJ..............rrrT',
  'T............JJJJ,JJJJ..............rrrT',
  'T.......................x.....^^^^^^rrrT',
  'T..T...........JJJJJ..........^^^^^^rrrT',
  'T..............JJJJJ..........WWWWWWrrrT',
  'T....T.........JJ1JJ..........WW22WWrrrT',
  '....................................rrrT',
  '....................................rrrT',
  'T...................................rrrT',
  'T........T.................T........rrrT',
  'T................................T..rrrT',
  'T.................YYYYY.............rrrT',
  'T.................YYYYY.............rrrT',
  'T..T..............YY4YY.............rrrT',
  'T.............M.....................rrrT',
  'T.............,.............T.......rrrT',
  'T.......T.....,................T....rrrT',
  'T.............,.........T...........rrrT',
  'T.............,.....................rrrT',
  'T.............,.....................rrrT',
  'TTTTTTTTTTTTT...TTTTTTTTTTTTTTTTTTTTrrrT',
];
// ゾーンD: 文化の家・中央図書館・桧ヶ根公園（実際に3施設が近接するエリア）
// F/^/1=文化の家, L/2=図書館, b/a=桧ヶ根公園（井伊直政陣地跡）
const ZONED = [
  'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
  'T......................................T',
  'T......................................T',
  'T......................................T',
  'T....T............................T....T',
  'T......................................T',
  'T...........^^^^^^^^^^^^^^^^...........T',
  'T...........^^^^^^^^^^^^^^^^...........T',
  'T...........^^^^^^^^^^^^^^^^...........T',
  'T...........FFFFFFFFFFFFFFFF...........T',
  'T...........FFFFFFFFFFFFFFFF..T........T',
  'T...........FFFFFFFFFFFFFFFF...........T',
  'T...........FFFFF111111FFFFF...........T',
  'T.......................................',
  'T.......................................',
  'T......................................T',
  'T.......T..............................T',
  'T..............................LLLLLLL.T',
  'T..............................LLLLLLL.T',
  'T..............................LLLLLLL.T',
  'T.....T................bbbbb...LLL2LLL.T',
  'T......................b...b...........T',
  'T..............T.......b.a.b...........T',
  'T...T..................b...b...........T',
  'T.........T............bbb.b.....T.....T',
  'T......................................T',
  'T......................................T',
  'TTTTTTTTTTTTTTTTTTT...TTTTTTTTTTTTTTTTTT',
];
// ゾーンE: モリコロパーク（西端でzoneGと地続き・リニモ終点）
const ZONEE = [
  'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
  'T......................................T',
  'T......................................T',
  'T...............................OOOO...T',
  'T...............................OOOO...T',
  'T...............................OOOO...T',
  'T...............................OOOO...T',
  'T......................................T',
  'T......................................T',
  'T.........p............................T',
  'T...........................q..........T',
  'T......................................T',
  'T.............~~~~~~~~~~~..............T',
  'T.............~~~~~~~~~~~..............T',
  'T.............~~~~~~~~~~~..............T',
  'T.............~~~~~~~~~~~..............T',
  'T.............~~~~~~~~~~~..............T',
  'T.............~~~~~~~~~~~..............T',
  'T....eee...............................T',
  'T....eee...............................T',
  '.......................................T',
  'rrrrrrrrrr..........u..................T',
  'rrrrrrrrrr.............................T',
  '.......................................T',
  'T......................................T',
  'T....T....T.............T....T.........T',
  'T......................................T',
  'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
];
// ゾーンF: 芸大通（トヨタ博物館・愛知県立芸術大学）新規
// W/^/t=トヨタ博物館, W/^/g=県芸大, e=芸大通駅
const ZONEF = [
  'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
  'T......................................T',
  'T.T......T.......T......T............T.T',
  'T....T...............T....^^^^^^^^^^...T',
  'T............T............^^^^^^^^^^...T',
  'T.........................WWWWWWWWWW...T',
  'T.........................WWWWWWWWWW..TT',
  'T.......................T.WWWWgWWWWW...T',
  'T.T...........................,........T',
  'T.............................,........T',
  'T................T............,....T...T',
  'T...T.........................,........T',
  'T......................T......,........T',
  'T.....^^^^^^^^^...............,........T',
  'T.....^^^^^^^^^...............,...T....T',
  'T.....WWWWWWWWW...............,........T',
  'T.....WWWWWWWWW...............,........T',
  'T.T...WWWWtWWWW...............,........T',
  'T..................eee........,........T',
  'T..................eee........,........T',
  '.................@......................',
  'rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr',
  'rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr',
  '........................................',
  'T........T.....................T.......T',
  'T...T...............T.....T............T',
  'T..............T....................T..T',
  'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
];
// ゾーンG: 公園西（IKEA長久手・平成こども塾）新規
// W/^/f=IKEA, K/3=こども塾（丸太の家）, e=公園西駅
const ZONEG = [
  'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
  'T......................................T',
  'T.T........T.........T.................T',
  'T.....T.........T........T.........T...T',
  'T......................................T',
  'T...........................KKKKK......T',
  'T...........................KKKKK......T',
  'T.........................T.KK3KK....T.T',
  'T..T..........................,........T',
  'T................T............,........T',
  'T.......................T.....,...T....T',
  'T.............................,........T',
  'T....^^^^^^^^^^...............,........T',
  'T....^^^^^^^^^^...............,........T',
  'T....WWWWWWWWWW...............,.....T..T',
  'T.T..WWWWWWWWWW...............,........T',
  'T....WWWWWWWWWW...............,........T',
  'T....WWWWfWWWWW...............,........T',
  'T.................eee.........,........T',
  'T.................eee.........,........T',
  '................@.......................',
  'rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr',
  'rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr',
  '........................................',
  'T....T..........T.............T........T',
  'T.......................T..........T...T',
  'T.........T............................T',
  'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
];
// 岩崎城址公園（日進市・ハードクリア後の裏イベント）
// W/5=模擬天守（本丸・空堀kに囲まれ土橋,で渡る）, F/6=歴史記念館, ~=二の丸庭園の池,
// n=学芸員・内貴, s=坂元, P=セーブ篝火, 7=帰りの案内板
const IWASAKI = [
  'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
  'T......................................T',
  'T..T.....T..........................T..T',
  'T......................................T',
  'T............kkkkkkkkkkkkk.............T',
  'T............k...........k.............T',
  'T............k...WWWWW...k.............T',
  'T............k...WWWWW...k.............T',
  'T............k...WWWWW...k.............T',
  'T............k...WW5WW...k.............T',
  'T............k...........k.............T',
  'T............kkkkkk,kkkkkk.............T',
  'T................n.,.s.................T',
  'T..T...............,..............T....T',
  'T..................,...................T',
  'T..................,...................T',
  'T.......~~~........,........FFFFFF.....T',
  'T.......~~~........,........FFFFFF.....T',
  'T..................,........FF6FFF.....T',
  'T.....bb...........,...................T',
  'T..................,......P............T',
  'T..................,...................T',
  'T..T...............,...........T.......T',
  'T..................,...................T',
  'T..................@...................T',
  'T..................,...................T',
  'T..................7...................T',
  'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
];
// 文化の家・1階ガレリア（吹き抜けの明るい廊下。V=森のホール, 1=風, 2=光, 3=展示, 4=小音楽, U=2階へ, D=外へ）
const BUNKA1 = [
  '####################',
  '##wwwVww1ww2ww3ww###',
  '#.U..............4.#',
  '#..................#',
  '#..................#',
  '#..................#',
  '#....b....b...b....#',
  '#..................#',
  '#..................#',
  '#..p...............#',
  '#..................#',
  '#..................#',
  '#......@...........#',
  '########DD##########',
];
// 文化の家・2階廊下（1=多目的, 2=講義, 3=食文化, 4=美術, 5=スタジオ, 6=暗室, 7=音楽室, 8=舞踊室,
// h/9=アーツライブラリー（オープンエリアの読書コーナー）, U=3階へ, W=1階へ）
const BUNKA2 = [
  '########################',
  '#....1..2..3..4..5.....#',
  '#.W..................U.#',
  '#......................#',
  '#......................#',
  '#......................#',
  '#..b.............hhhhhh#',
  '#......@...............#',
  '#......................#',
  '#..p.............tt..tt#',
  '#......................#',
  '#..................9...#',
  '#......................#',
  '#####6###7###8##########',
];
const MORIHALL = [
  '################',
  '#==============#',
  '#==============#',
  '#..............#',
  '#.......s......#',
  '#..............#',
  '#......@.......#',
  '#..............#',
  '#..............#',
  '#..............#',
  '#..............#',
  '#..............#',
  '#..............#',
  '#######DD#######',
];
// イオンモール長久手・店内（w=フードコートの大窓, t=テーブル, h=イオンスタイル売場の棚,
// c/8=レジと店員, b=ベンチ, p=館内案内板）
const AEON_IN = [
  '################',
  '#wwwwwwwwwwwwww#',
  '#.tt..tt..tt...#',
  '#.tt..tt..tt...#',
  '#..............#',
  '#hh.hh...cc8cc.#',
  '#hh.hh.........#',
  '#hh.hh....b.b..#',
  '#..............#',
  '#hh.hh....p....#',
  '#hh.hh.........#',
  '#..............#',
  '#......@.......#',
  '#######DD#######',
];
// 一蘭 長久手店・店内（k=厨房, q=味集中カウンター(27席), 8=店員, y=食券機, p=空席案内板）
const RAMEN_IN = [
  '################',
  '#kkkkkkkkkkkkkk#',
  '#qqqqqqqqqqqqqq#',
  '#.......8......#',
  '#..............#',
  '#qqqqqqqqqqqqq.#',
  '#..............#',
  '#..............#',
  '#..............#',
  '#..............#',
  '#..............#',
  '#.y.........p..#',
  '#......@.......#',
  '#######DD#######',
];
// 長久手市役所・1階ロビー（c=窓口カウンター, 8=市民課職員(長久手検定), 9=総合案内,
// y=番号札発券機, b=待合ソファ, p=掲示板）
const CITYHALL_IN = [
  '################',
  '#ppp......ppp..#',
  '#..............#',
  '#cc8cc...cc9cc.#',
  '#..............#',
  '#.y............#',
  '#..b..b..b.....#',
  '#..b..b..b.....#',
  '#..............#',
  '#..............#',
  '#..............#',
  '#..............#',
  '#......@.......#',
  '#######DD#######',
];
// 長久手市中央図書館・1階（h=書架(右=一般・左下=児童), c/8=貸出カウンターと司書,
// 9=絵本コーナーの子, t=閲覧席）
const LIBRARY_IN = [
  '################',
  '#hhhh.hhhh.hhhh#',
  '#..............#',
  '#hhhh.hhhh.hhhh#',
  '#..............#',
  '#.....cc8cc....#',
  '#..............#',
  '#tt..........hh#',
  '#tt....9.....hh#',
  '#..............#',
  '#hh.hh....tt...#',
  '#..............#',
  '#......@.......#',
  '#######DD#######',
];
// 色金山歴史公園・茶室「胡牀庵」（如庵写し。z=畳, Z=床の間, x=炉, t=立礼席,
// 8=亭主(抹茶体験500円), k=水屋, w=庭の見える窓）
const TEAROOM_IN = [
  '################',
  '#ZZzzz....www..#',
  '#zzzzz.........#',
  '#zzxzz...tt.tt.#',
  '#zzzzz...tt.tt.#',
  '#zzzzz.....8...#',
  '#..............#',
  '#.....k........#',
  '#..............#',
  '#..............#',
  '#..............#',
  '#..............#',
  '#......@.......#',
  '#######DD#######',
];
// 平成こども塾「丸太の家」・内部（東濃ひのきの大空間。t=作業台, h=作品棚,
// k=かまどコーナー, 8=スタッフ(兵糧丸づくり)）
const KODOMO_IN = [
  '################',
  '#hhhh......kk..#',
  '#..........kk..#',
  '#..............#',
  '#..tttt..tttt..#',
  '#..tttt..tttt..#',
  '#..............#',
  '#......8.......#',
  '#hh............#',
  '#..............#',
  '#..............#',
  '#..............#',
  '#......@.......#',
  '#######DD#######',
];
// 岩崎城歴史記念館・展示室（g=展示ケース(甲冑・采配・出土品), j=動くジオラマ(三河中入),
// m=甲冑試着コーナー, c/8=受付(御城印), p=解説パネル）
const IWKIN_IN = [
  '################',
  '#p.ggg.ggg...p.#',
  '#..............#',
  '#....jjj.......#',
  '#....jjj.......#',
  '#..............#',
  '#.mm...........#',
  '#..............#',
  '#..............#',
  '#....cc8cc.....#',
  '#..............#',
  '#..............#',
  '#......@.......#',
  '#######DD#######',
];
// 岩崎城 模擬天守・展望室（f=金網の展望窓(360度), o=望遠鏡, p=縄張り解説パネル,
// D=階段(下りる)）
const TENSHU_IN = [
  '################',
  '#ffffffffffffff#',
  '#f............f#',
  '#f............f#',
  '#....o.....o...#',
  '#..............#',
  '#..............#',
  '#.....pp.......#',
  '#..............#',
  '#f............f#',
  '#f............f#',
  '#ffffff..ffffff#',
  '#......@.......#',
  '#######DD#######',
];
// リニモ駅・ホーム階（島式1面2線・全駅共通。r=線路, e=可動式ホーム柵(乗車はここでZ),
// p=行先案内サイン, D=階段(改札へ下りる)。どの駅にいるかは game.js の stationAt が保持）
const STATION_HOME = [
  '################',
  '#rrrrrrrrrrrrrr#',
  '#eeeeeeeeeeeeee#',
  '#..............#',
  '#..p.......p...#',
  '#..............#',
  '#......DD......#',
  '#......@.......#',
  '#..p.......p...#',
  '#..............#',
  '#eeeeeeeeeeeeee#',
  '#rrrrrrrrrrrrrr#',
  '#..............#',
  '################',
];
// 色金山ダンジョン・登山道（つづら折り。v=下山口(zoneCへ), 5=山頂への石段, J=岩壁）
const IROGANE1 = [
  'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
  'T......................................T',
  'T.......T...........8.......T..........T',
  'T............T......,,,,R,,,,,,,b,,,...T',
  'T..................................,...T',
  'TJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ..JJJT',
  'TJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ..JJJT',
  'T...,.........T.........T......T...,...T',
  'T...,,,,,,,R,,,,,,,,,,,,,,,R,,b,,,,,...T',
  'T...,..................................T',
  'TJJJ..JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJT',
  'TJJJ..JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJT',
  'T...,....T..........T.......T......,...T',
  'T...,,,,,,,,,,,b,,,,,,,,,,,,,,,,,R,,...T',
  'T.................R................,...T',
  'TJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ..JJJT',
  'TJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ..JJJT',
  'T...,.......T...........T.....T....,...T',
  'T...,,,,,,,,,,,,,,,,,,,,,b,,,,,,,,,,...T',
  'T...,..R.....................R.........T',
  'TJJJ..JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJT',
  'TJJJ..JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJT',
  'T...,..................................T',
  'T...,....T................T.........T..T',
  'T...,,,,,,,,,b,,,,....R........T.......T',
  'T................@.....................T',
  'T................9.....................T',
  'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
];
// 色金山ダンジョン・山頂（R=床机石(史跡クイズ＋戦闘), o=展望盤(展望台), ==木デッキ, P=セーブ篝火, v=下山口）
const IROGANE2 = [
  'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
  'TJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJT',
  'TJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJT',
  'TJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJT',
  'TJJJJJJ..........................JJJJJJT',
  'TJJJJJJ.T.............T..........JJJJJJT',
  'TJJJJJJ.....R...........=======..JJJJJJT',
  'TJJJJJJ.....,...........===o===..JJJJJJT',
  'TJJJJJJ.....,...........=======..JJJJJJT',
  'TJJJJJJ.....,...........=======..JJJJJJT',
  'TJJJJJJ.................=======..JJJJJJT',
  'TJJJJJJ..........................JJJJJJT',
  'TJJJJJJ.........P................JJJJJJT',
  'TJJJJJJ............,.............JJJJJJT',
  'TJJJJJJ............,.............JJJJJJT',
  'TJJJJJJ..T.........,.........T...JJJJJJT',
  'TJJJJJJ............,.....b.......JJJJJJT',
  'TJJJJJJ.......b....,.............JJJJJJT',
  'TJJJJJJ..T.........,..........T..JJJJJJT',
  'TJJJJJJ............@.............JJJJJJT',
  'TJJJJJJ............9.............JJJJJJT',
  'TJJJJJJ..........................JJJJJJT',
  'TJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJT',
  'TJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJT',
  'TJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJT',
  'TJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJT',
  'TJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJT',
  'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
];
// 文化の家・3階廊下（静かなフロア。1=会議室, 2=和室, W=2階へ）
const BUNKA3 = [
  '################',
  '#...ww.1....2..#',
  '#.W............#',
  '#..............#',
  '#..............#',
  '#..............#',
  '#..............#',
  '#...b......p...#',
  '#..............#',
  '#..............#',
  '#..............#',
  '#......@.......#',
  '#..............#',
  '################',
];
// 文化の家・風のホール（プロセニアム舞台・音響反射板・段状292席・グランドピアノ）
const BK_KAZE = [
  '################',
  '#.vvvvvvvvvvvv.#',
  '#.============.#',
  '#.=====P======.#',
  '#p.............#',
  '#..............#',
  '#.iiiiiiiiiiii.#',
  '#..............#',
  '#.iiiiiiiiiiii.#',
  '#..............#',
  '#.iiiiiiiiiiii.#',
  '#..............#',
  '#......@.......#',
  '#######DD#######',
];
// 文化の家・光のホール（200インチスクリーンv・小舞台・テーブル付き階段席・0=職員くろの）
const BK_HIKARI = [
  '################',
  '#.vvvvvvvvvvvv.#',
  '#.vvvvvvvvvvvv.#',
  '#..............#',
  '#.============.#',
  '#...........0..#',
  '#..............#',
  '#piiiiiiiiiiii.#',
  '#..............#',
  '#.iiiiiiiiiiii.#',
  '#..............#',
  '#.iiiiiiiiiiii.#',
  '#......@.......#',
  '#######DD#######',
];
// 文化の家・展示室（壁面フックの額装展示・イーゼルE・丸テーブル）
const BK_TENJI = [
  '################',
  '#.gggggggggggg.#',
  '#..............#',
  '#..............#',
  '#..............#',
  '#..E....E...E..#',
  '#..............#',
  '#..............#',
  '#.b....t....b..#',
  '#..............#',
  '#..............#',
  '#..............#',
  '#......@.......#',
  '#######DD#######',
];
// 文化の家・小音楽室（アップライトピアノu・譜面台E・防音窓）
const BK_SHOON = [
  '################',
  '#.....wwwww....#',
  '#..u...........#',
  '#......E..E....#',
  '#..............#',
  '#..............#',
  '#....bbbbbb....#',
  '#..............#',
  '#..............#',
  '#..............#',
  '#..............#',
  '#..............#',
  '#......@.......#',
  '#######DD#######',
];
// 文化の家・多目的室（簡易防音・長机・椅子）
const BK_TAMOKU = [
  '################',
  '#..wwwwwwwwww..#',
  '#...........E..#',
  '#..............#',
  '#...tttttttt...#',
  '#..............#',
  '#...bbbbbbbb...#',
  '#..............#',
  '#..............#',
  '#..............#',
  '#..............#',
  '#..............#',
  '#......@.......#',
  '#######DD#######',
];
// 文化の家・講義室（ホワイトボードp・スクリーンv・長机列・0=受講者）
const BK_KOUGI = [
  '################',
  '#..pppppp.vvvv.#',
  '#..............#',
  '#..............#',
  '#..tttttttttt..#',
  '#..............#',
  '#..tttttttttt..#',
  '#..............#',
  '#..tttttttttt..#',
  '#..............#',
  '#..............#',
  '#............0.#',
  '#......@.......#',
  '#######DD#######',
];
// 文化の家・食文化室（調理台6台k・試食テーブル・配膳カウンター）
const BK_SHOKU = [
  '################',
  '#.kkkkkkkkkkkk.#',
  '#..............#',
  '#..............#',
  '#..kk..kk..kk.c#',
  '#..............#',
  '#..............#',
  '#..kk..kk..kk..#',
  '#..............#',
  '#..............#',
  '#...tttttttt...#',
  '#..............#',
  '#......@.......#',
  '#######DD#######',
];
// 文化の家・美術室（作業台・イーゼルE・洗い場k・0=絵を描く人）
const BK_BIJUTSU = [
  '################',
  '#..............#',
  '#..tttt..E..E..#',
  '#..............#',
  '#..............#',
  '#.ttt..ttt.ttt.#',
  '#..............#',
  '#..............#',
  '#.ttt..ttt.ttt.#',
  '#..............#',
  '#...0.........k#',
  '#..............#',
  '#......@.......#',
  '#######DD#######',
];
// 文化の家・音楽スタジオ（ドラムセットd=調べると鳴る・アンプa・電子ピアノu・ミキサーc）
const BK_STUDIO = [
  '################',
  '#..............#',
  '#..a...d...a...#',
  '#..............#',
  '#..............#',
  '#..u.......c...#',
  '#..............#',
  '#..............#',
  '#..............#',
  '#..............#',
  '#..............#',
  '#..............#',
  '#......@.......#',
  '#######DD#######',
];
// 文化の家・暗室（細長10㎡・引伸ばし機y×2・現像バットn・ドライヤーk。画面が赤暗くなる）
const BK_ANSHITSU = [
  '################',
  '################',
  '################',
  '################',
  '#..y.y..nnnnn.k#',
  '#..............#',
  '#..............#',
  '#..............#',
  '#..............#',
  '#..............#',
  '#######..###...#',
  '#######..###...#',
  '#######@.###...#',
  '#######DD#######',
];
// 文化の家・音楽室（グランドP＋アップライトu・譜面台E・0=練習中の学生）
const BK_ONGAKU = [
  '################',
  '#..............#',
  '#p..P.......u..#',
  '#..............#',
  '#..............#',
  '#..E..E..E..E..#',
  '#..............#',
  '#..............#',
  '#..bbbbbbb0bb..#',
  '#..............#',
  '#..............#',
  '#..............#',
  '#......@.......#',
  '#######DD#######',
];
// 文化の家・舞踊室（鏡張りM＋バレエバー・スピーカーa×4・更衣室2・0=ダンサー）
const BK_BUYOU = [
  '################',
  '#.MMMMMMMMMMMM.#',
  '#a............a#',
  '#..............#',
  '#..............#',
  '#..............#',
  '#2........0...2#',
  '#..............#',
  '#..............#',
  '#..............#',
  '#a............a#',
  '#..............#',
  '#......@.......#',
  '#######DD#######',
];
// 文化の家・会議室（3階・会議テーブル・ホワイトボード）
const BK_KAIGI = [
  '################',
  '#....pppppp....#',
  '#..............#',
  '#..............#',
  '#...tttttttt...#',
  '#..b........b..#',
  '#..............#',
  '#...tttttttt...#',
  '#..............#',
  '#..............#',
  '#..............#',
  '#..............#',
  '#......@.......#',
  '#######DD#######',
];
// 文化の家・和室（6畳＋8畳z・ふすまq・床の間Z・炉x・水屋k・座卓t・0=お茶の人）
const BK_WASHITSU = [
  '################',
  '#zZzzzzFzzzzzzk#',
  '#zzzzzzFzzzzzzz#',
  '#zzzzzzFzzzxzzz#',
  '#zztzzzFzzzzzzz#',
  '#zzzzzzFzzzzzzz#',
  '#zzzzzzFzztzzzz#',
  '#zzzzzzzzzzzzzz#',
  '#zzztzzzzzzz0zz#',
  '#zzzzzzzzzzzzzz#',
  '#zzzzzzzzzzzzzz#',
  '#..............#',
  '#......@.......#',
  '#######DD#######',
];
// マップレジストリ。新マップは rows＋この定義を追加するだけで動く。
//  kind: outdoor はカメラスクロール対象（画面より大きい場合）、indoor は固定画面
//  tileset: drawTile の描画スタイル（museum / outdoor。将来 mall / library 等を追加）
//  solid: 通行不可文字、npcs: NPC文字→{kind,id,floor}、acts: アクション文字→ID
//  encounter: { rate } でエンカウント有効（null なら無効）
const MAP_DEFS = {
  museum: {
    rows: MUSEUM, kind: 'indoor', tileset: 'museum', playerFloor: '.',
    solid: ['#', 'B', 'K', 'S', 'D'],
    npcs: {},
    acts: { B: 'byobu', K: 'katchu', S: 'katana', D: 'museum_exit', P: 'save' },
    encounter: null,
  },
  field: {
    rows: FIELD, kind: 'outdoor', tileset: 'outdoor', playerFloor: ',',
    solid: ['T', '~', 'M', 'P'],
    npcs: { i: { kind: 'ike', id: 'ike', floor: '.' }, m: { kind: 'michi', id: 'michi', floor: ',' } },
    acts: { M: 'mound', P: 'save' },
    encounter: { rate: 0.07 },
  },
  zoneA: {
    rows: ZONEA, kind: 'outdoor', tileset: 'outdoor', playerFloor: '.',
    solid: ['T', '~', 'M', 'N', 'R', 'b', 'W', '^', 'D', 'P', 'I', '4', 'e'],
    npcs: {},
    acts: { M: 'mound', N: 'shokuro', R: 'rock', D: 'museum_enter', P: 'save', 4: 'aeon', e: 'station', a: 'site_chinoike' },
    edges: {
      west: { map: 'zoneC', spawn: { col: 35, row: 14 } },
      north: { map: 'zoneF', spawn: { col: 22, row: 20 } },
      south: { map: 'zoneB', spawn: { col: 13, row: 20 } },
    },
    encounter: { rate: 0.03, afterUnlock: true },
  },
  zoneB: {
    rows: ZONEB, kind: 'outdoor', tileset: 'outdoor', playerFloor: '.',
    solid: ['T', 'b', '~', 'N', 'W', '^', 'e'],
    npcs: {},
    acts: { N: 'site_mihata', a: 'flavor_iriga', e: 'station' },
    edges: { east: { map: 'zoneA', spawn: { col: 36, row: 25 } }, north: 'zoneD' },
    encounter: { rate: 0.04, afterUnlock: true },
  },
  zoneC: {
    rows: ZONEC, kind: 'outdoor', tileset: 'outdoor', playerFloor: '.',
    solid: ['T', 'M', 'R', 'J', 'W', '^', '1', '2', 'x', 'Y', '4', 'h'],
    npcs: {},
    acts: { R: 'irogane_in', 1: 'tearoom', 2: 'cityhall', 4: 'ramen', o: 'site_ansho', M: 'site_musashi', x: 'shateki', h: 'flavor_aidai' },
    edges: { south: { map: 'zoneA', spawn: { col: 1, row: 9 } }, west: 'zoneD' },
    encounter: { rate: 0.045, afterUnlock: true },
  },
  zoneD: {
    rows: ZONED, kind: 'outdoor', tileset: 'outdoor', playerFloor: '.',
    solid: ['T', 'F', '^', 'L', '1', '2', 'b'],
    npcs: {},
    acts: { 1: 'bunka_in', 2: 'library', a: 'higane' },
    edges: { east: 'zoneC', south: 'zoneB' },
    encounter: { rate: 0.04, afterUnlock: true },
  },
  zoneE: {
    rows: ZONEE, kind: 'outdoor', tileset: 'outdoor', playerFloor: '.',
    solid: ['T', '~', 'O', 'e'],
    npcs: {
      p: { kind: 'civ1', id: 'expo1', floor: '.' },
      q: { kind: 'civ2', id: 'expo2', floor: '.' },
      u: { kind: 'civ1', id: 'expo3', floor: '.' },
    },
    acts: { e: 'station', O: 'wheel' },
    edges: { west: 'zoneG' },
    encounter: null,
  },
  zoneF: {
    rows: ZONEF, kind: 'outdoor', tileset: 'outdoor', playerFloor: '.',
    solid: ['T', 'W', '^', 't', 'g', 'e'],
    npcs: {},
    acts: { t: 'flavor_toyota', g: 'flavor_geidai', e: 'station' },
    edges: { west: { map: 'zoneA', spawn: { col: 36, row: 2 } }, east: 'zoneG' },
    encounter: { rate: 0.05, afterUnlock: true },
  },
  zoneG: {
    rows: ZONEG, kind: 'outdoor', tileset: 'outdoor', playerFloor: '.',
    solid: ['T', 'W', '^', 'K', '3', 'f', 'e'],
    npcs: {},
    acts: { 3: 'kodomo', f: 'flavor_ikea', e: 'station' },
    edges: { west: 'zoneF', east: 'zoneE' },
    encounter: { rate: 0.05, afterUnlock: true },
  },
  aeon_in: {
    rows: AEON_IN, kind: 'indoor', tileset: 'museum', playerFloor: '.',
    solid: ['#', 'w', 't', 'h', 'c', 'b', 'p', 'D'],
    npcs: { 8: { kind: 'civ8', id: 'aeon_clerk', floor: '.' } },
    acts: { D: 'aeon_exit', p: 'aeon_info' },
    encounter: null,
  },
  ramen_in: {
    rows: RAMEN_IN, kind: 'indoor', tileset: 'museum', playerFloor: '.',
    solid: ['#', 'k', 'q', 'y', 'p', 'D'],
    npcs: { 8: { kind: 'civ8', id: 'ramen_clerk', floor: '.' } },
    acts: { D: 'ramen_exit', y: 'ramen_ticket', p: 'ramen_board' },
    encounter: null,
  },
  cityhall_in: {
    rows: CITYHALL_IN, kind: 'indoor', tileset: 'museum', playerFloor: '.',
    solid: ['#', 'c', 'y', 'b', 'p', 'D'],
    npcs: {
      8: { kind: 'civ6', id: 'cityhall_clerk', floor: '.' },
      9: { kind: 'civ3', id: 'cityhall_info', floor: '.' },
    },
    acts: { D: 'cityhall_exit', y: 'cityhall_ticket', p: 'cityhall_post' },
    encounter: null,
  },
  library_in: {
    rows: LIBRARY_IN, kind: 'indoor', tileset: 'museum', playerFloor: '.',
    solid: ['#', 'h', 'c', 't', 'D'],
    npcs: {
      8: { kind: 'civ2', id: 'library_clerk', floor: '.' },
      9: { kind: 'civ4', id: 'library_kid', floor: '.' },
    },
    acts: { D: 'library_exit' },
    encounter: null,
  },
  tearoom_in: {
    rows: TEAROOM_IN, kind: 'indoor', tileset: 'museum', playerFloor: '.',
    solid: ['#', 'Z', 'x', 'w', 't', 'k', 'D'],
    npcs: { 8: { kind: 'civ3', id: 'tea_host', floor: '.' } },
    acts: { D: 'tearoom_exit', Z: 'tearoom_toko', x: 'tearoom_ro', k: 'tearoom_mizuya' },
    encounter: null,
  },
  kodomo_in: {
    rows: KODOMO_IN, kind: 'indoor', tileset: 'museum', playerFloor: '.',
    solid: ['#', 'h', 't', 'k', 'D'],
    npcs: { 8: { kind: 'civ8', id: 'kodomo_staff', floor: '.' } },
    acts: { D: 'kodomo_exit', k: 'kodomo_kamado' },
    encounter: null,
  },
  iwkin_in: {
    rows: IWKIN_IN, kind: 'indoor', tileset: 'museum', playerFloor: '.',
    solid: ['#', 'g', 'j', 'c', 'p', 'D'],
    npcs: { 8: { kind: 'civ2', id: 'iwkin_clerk', floor: '.' } },
    acts: { D: 'iwkin_exit', g: 'iwkin_case', j: 'iwkin_diorama', m: 'iwkin_dressup', p: 'iwkin_panel' },
    encounter: null,
  },
  tenshu_in: {
    rows: TENSHU_IN, kind: 'indoor', tileset: 'museum', playerFloor: '.',
    solid: ['#', 'f', 'o', 'p', 'D'],
    npcs: {},
    acts: { D: 'tenshu_exit', f: 'tenshu_kanamori', o: 'tenshu_scope', p: 'tenshu_map' },
    encounter: null,
  },
  station_home: {
    rows: STATION_HOME, kind: 'indoor', tileset: 'museum', playerFloor: '.',
    solid: ['#', 'r', 'e', 'p', 'D'],
    npcs: {},
    acts: { D: 'station_exit', e: 'station_board', p: 'station_sign' },
    encounter: null,
  },
  irogane1: {
    rows: IROGANE1, kind: 'outdoor', tileset: 'outdoor', playerFloor: '.',
    solid: ['T', 'J', 'R', 'b', '8', '9'],
    npcs: {},
    acts: { 8: 'irogane_up', 9: 'irogane_exit' },
    encounter: { rate: 0.06 },
  },
  irogane2: {
    rows: IROGANE2, kind: 'outdoor', tileset: 'outdoor', playerFloor: '.',
    solid: ['T', 'J', 'R', 'b', 'o', 'P', '8', '9'],
    npcs: {},
    acts: { R: 'site_irogane', 9: 'irogane_down', o: 'irogane_view', P: 'save' },
    encounter: null,
  },
  bunka1: {
    rows: BUNKA1, kind: 'indoor', tileset: 'museum', playerFloor: '.',
    solid: ['#', 'D', 'U', 'V', 'w', 'b', 'p', '1', '2', '3', '4'],
    npcs: {},
    acts: { D: 'bunka_exit', U: 'bunka_up', V: 'mori_in', 1: 'bk_kaze_in', 2: 'bk_hikari_in', 3: 'bk_tenji_in', 4: 'bk_shoon_in', p: 'bunka_map1' },
    encounter: null,
  },
  bunka2: {
    rows: BUNKA2, kind: 'indoor', tileset: 'museum', playerFloor: '.',
    solid: ['#', 'U', 'W', 'w', 'b', 'p', 'h', 't', '9', '1', '2', '3', '4', '5', '6', '7', '8'],
    npcs: {},
    acts: { U: 'bunka_up3', W: 'bunka_down', 1: 'bk_tamoku_in', 2: 'bk_kougi_in', 3: 'bk_shoku_in', 4: 'bk_bijutsu_in', 5: 'bk_studio_in', 6: 'bk_anshitsu_in', 7: 'bk_ongaku_in', 8: 'bk_buyou_in', 9: 'arts_library', h: 'arts_library', p: 'bunka_map2' },
    encounter: null,
  },
  bunka3: {
    rows: BUNKA3, kind: 'indoor', tileset: 'museum', playerFloor: '.',
    solid: ['#', 'W', 'w', 'b', 'p', '1', '2'],
    npcs: {},
    acts: { W: 'bunka_down3', 1: 'bk_kaigi_in', 2: 'bk_washitsu_in', p: 'bunka_map3' },
    encounter: null,
  },
  bk_kaze: {
    rows: BK_KAZE, kind: 'indoor', tileset: 'museum', playerFloor: '.',
    solid: ['#', 'D', 'v', '=', 'P', 'i', 'p'],
    npcs: {},
    acts: { D: 'bk_room_exit', P: 'bk_kaze_piano', v: 'bk_kaze_stage', i: 'bk_seats', p: 'bk_kaze_light' },
    encounter: null,
  },
  bk_hikari: {
    rows: BK_HIKARI, kind: 'indoor', tileset: 'museum', playerFloor: '.',
    solid: ['#', 'D', 'v', '=', 'i', 'p'],
    npcs: { 0: { kind: 'kurono', id: 'kurono', floor: '.' } },
    acts: { D: 'bk_room_exit', v: 'bk_hikari_screen', i: 'bk_seats', p: 'bk_hikari_proj' },
    encounter: null,
  },
  bk_tenji: {
    rows: BK_TENJI, kind: 'indoor', tileset: 'museum', playerFloor: '.',
    solid: ['#', 'D', 'g', 'E', 't', 'b'],
    npcs: {},
    acts: { D: 'bk_room_exit', g: 'bk_tenji_works', E: 'bk_easel', t: 'bk_tenji_table' },
    encounter: null,
  },
  bk_shoon: {
    rows: BK_SHOON, kind: 'indoor', tileset: 'museum', playerFloor: '.',
    solid: ['#', 'D', 'u', 'E', 'b', 'w'],
    npcs: {},
    acts: { D: 'bk_room_exit', u: 'bk_upright', E: 'bk_stand' },
    encounter: null,
  },
  bk_tamoku: {
    rows: BK_TAMOKU, kind: 'indoor', tileset: 'museum', playerFloor: '.',
    solid: ['#', 'D', 't', 'b', 'E', 'w'],
    npcs: {},
    acts: { D: 'bk_room_exit', t: 'bk_tamoku_desk', E: 'bk_stand' },
    encounter: null,
  },
  bk_kougi: {
    rows: BK_KOUGI, kind: 'indoor', tileset: 'museum', playerFloor: '.',
    solid: ['#', 'D', 'p', 'v', 't'],
    npcs: { 0: { kind: 'civ3', id: 'bk_mob_kougi', floor: '.' } },
    acts: { D: 'bk_room_exit', p: 'bk_whiteboard', v: 'bk_kougi_screen', t: 'bk_kougi_desk' },
    encounter: null,
  },
  bk_shoku: {
    rows: BK_SHOKU, kind: 'indoor', tileset: 'museum', playerFloor: '.',
    solid: ['#', 'D', 'k', 't', 'c'],
    npcs: {},
    acts: { D: 'bk_room_exit', k: 'bk_shoku_daidokoro', t: 'bk_shoku_table', c: 'bk_shoku_counter' },
    encounter: null,
  },
  bk_bijutsu: {
    rows: BK_BIJUTSU, kind: 'indoor', tileset: 'museum', playerFloor: '.',
    solid: ['#', 'D', 't', 'E', 'k'],
    npcs: { 0: { kind: 'civ2', id: 'bk_mob_bijutsu', floor: '.' } },
    acts: { D: 'bk_room_exit', t: 'bk_bijutsu_desk', E: 'bk_easel', k: 'bk_bijutsu_sink' },
    encounter: null,
  },
  bk_studio: {
    rows: BK_STUDIO, kind: 'indoor', tileset: 'museum', playerFloor: '.',
    solid: ['#', 'D', 'd', 'a', 'u', 'c'],
    npcs: {},
    acts: { D: 'bk_room_exit', d: 'bk_studio_drum', a: 'bk_studio_amp', u: 'bk_studio_piano', c: 'bk_studio_mixer' },
    encounter: null,
  },
  bk_anshitsu: {
    rows: BK_ANSHITSU, kind: 'indoor', tileset: 'museum', playerFloor: '.',
    solid: ['#', 'D', 'y', 'n', 'k'],
    npcs: {},
    acts: { D: 'bk_room_exit', y: 'bk_anshitsu_enlarger', n: 'bk_anshitsu_bat', k: 'bk_anshitsu_dryer' },
    encounter: null,
  },
  bk_ongaku: {
    rows: BK_ONGAKU, kind: 'indoor', tileset: 'museum', playerFloor: '.',
    solid: ['#', 'D', 'P', 'u', 'E', 'b', 'p'],
    npcs: { 0: { kind: 'civ7', id: 'bk_mob_ongaku', floor: '.' } },
    acts: { D: 'bk_room_exit', P: 'bk_grand_piano', u: 'bk_upright', E: 'bk_stand', p: 'bk_whiteboard' },
    encounter: null,
  },
  bk_buyou: {
    rows: BK_BUYOU, kind: 'indoor', tileset: 'museum', playerFloor: '.',
    solid: ['#', 'D', 'M', 'a', '2'],
    npcs: { 0: { kind: 'civ5', id: 'bk_mob_buyou', floor: '.' } },
    acts: { D: 'bk_room_exit', M: 'bk_buyou_mirror', a: 'bk_buyou_speaker', 2: 'bk_buyou_locker' },
    encounter: null,
  },
  bk_kaigi: {
    rows: BK_KAIGI, kind: 'indoor', tileset: 'museum', playerFloor: '.',
    solid: ['#', 'D', 'p', 't', 'b'],
    npcs: {},
    acts: { D: 'bk_room_exit', p: 'bk_whiteboard', t: 'bk_kaigi_desk' },
    encounter: null,
  },
  bk_washitsu: {
    rows: BK_WASHITSU, kind: 'indoor', tileset: 'museum', playerFloor: '.',
    solid: ['#', 'D', 'Z', 'x', 'k', 't', 'F'],
    npcs: { 0: { kind: 'civ3', id: 'bk_mob_washitsu', floor: 'z' } },
    acts: { D: 'bk_room_exit', Z: 'bk_washitsu_toko', x: 'bk_washitsu_ro', k: 'bk_washitsu_mizuya', t: 'bk_washitsu_zataku', F: 'bk_washitsu_fusuma' },
    encounter: null,
  },
  mori: {
    rows: MORIHALL, kind: 'indoor', tileset: 'museum', playerFloor: '.',
    npcs: { s: { kind: 'sakamoto', id: 'sakamoto', floor: '.' } },
    solid: ['#', 'D', '='],
    acts: { D: 'mori_exit', '=': 'drumcircle' },
    encounter: null,
  },
  iwasaki: {
    rows: IWASAKI, kind: 'outdoor', tileset: 'outdoor', playerFloor: '.',
    solid: ['T', '~', 'W', '5', 'F', '6', 'k', 'P', '7', 'b'],
    npcs: { n: { kind: 'naiki', id: 'naiki', floor: '.' }, s: { kind: 'sakamoto', id: 'sakamoto_iw', floor: '.' } },
    acts: { 5: 'tenshu', 6: 'iwasaki_kinenkan', P: 'save', 7: 'iwasaki_gate' },
    encounter: { rate: 0.055 },
  },
};

// 装飾スプライトの描画定義（w=タイル幅の倍率。高さは画像アスペクトから算出し底辺で接地）
const HD_DECO_DEF = {
  T: { key: 'tree', w: 1.55 },
  b: { key: 'bush', w: 1.2 },
  R: { key: 'rock', w: 1.1 },
  M: { key: 'mound', w: 1.4 },
  N: { key: 'mound_s', w: 1.2 },
};
// 建物一枚絵の配置（タイル矩形）。画像は横幅にフィットし、余った高さは上（屋根方向）へはみ出す
// 画像が未導入の建物（toyota / ikea / geidai / aidai）は W/^ タイルのプロシージャル描画で代替される
const HD_BLD_DEF = {
  zoneA: [
    { key: 'aeon', c0: 4, r0: 2, w: 7, h: 5 },
    { key: 'station', c0: 32, r0: 6, w: 3, h: 3 },
    { key: 'museum', c0: 12, r0: 14, w: 13, h: 6 },
  ],
  zoneB: [{ key: 'station', c0: 10, r0: 18, w: 3, h: 2 }],
  zoneC: [
    { key: 'temple', c0: 4, r0: 4, w: 5, h: 3 },
    { key: 'tearoom', c0: 15, r0: 10, w: 5, h: 3 },
    { key: 'cityhall', c0: 30, r0: 9, w: 6, h: 4 },
    { key: 'ramen', c0: 18, r0: 18, w: 5, h: 3 },
    { key: 'aidai', c0: 29, r0: 2, w: 7, h: 4 },
  ],
  zoneD: [
    { key: 'bunka', c0: 12, r0: 6, w: 16, h: 7 },
    { key: 'library', c0: 31, r0: 17, w: 7, h: 4 },
  ],
  zoneE: [
    { key: 'ferris', c0: 32, r0: 3, w: 4, h: 4 },
    { key: 'station', c0: 5, r0: 18, w: 3, h: 2 },
  ],
  zoneF: [
    { key: 'station', c0: 19, r0: 18, w: 3, h: 2 },
    { key: 'toyota', c0: 6, r0: 13, w: 9, h: 5 },
    { key: 'geidai', c0: 26, r0: 3, w: 10, h: 5 },
  ],
  zoneG: [
    { key: 'station', c0: 18, r0: 18, w: 3, h: 2 },
    { key: 'ikea', c0: 5, r0: 12, w: 10, h: 6 },
    { key: 'kodomo', c0: 28, r0: 5, w: 5, h: 3 },
  ],
  irogane1: [{ id: 'chagama', w: 35 }, { id: 'sabiyari', w: 35 }, { id: 'hagure', w: 30, mate: 'monomi' }],
  iwasaki: [
    { key: 'iwasaki_tenshu', c0: 17, r0: 6, w: 5, h: 4 },
    { key: 'iwasaki_kinenkan', c0: 28, r0: 16, w: 6, h: 3 },
  ],
};

// リニモ（愛知高速交通東部丘陵線）: 駅の定義と高架軌道の描画範囲
// 駅で Z → 路線図から行き先を選んで移動する（game.js の station アクション）
const LINIMO_STATIONS = [
  { id: 'iriga', name: '杁ヶ池公園', map: 'zoneB', col: 11, row: 20 },
  { id: 'kosenjo', name: '長久手古戦場', map: 'zoneA', col: 33, row: 9 },
  { id: 'geidai', name: '芸大通', map: 'zoneF', col: 20, row: 20 },
  { id: 'koennishi', name: '公園西', map: 'zoneG', col: 19, row: 20 },
  { id: 'expo', name: '愛・地球博記念公園', map: 'zoneE', col: 6, row: 20 },
];
// 高架軌道: 通常は横方向。zoneA だけ現地配置に合わせて縦方向（col は軌道中心列）
const LINIMO_TRACK = {
  zoneB: { c0: 0, c1: 39, row: 21.5 },
  zoneA: { orientation: 'vertical', col: 36, r0: 0, r1: 31 },
  zoneF: { c0: 0, c1: 39, row: 21.5 },
  zoneG: { c0: 0, c1: 39, row: 21.5 },
  zoneE: { c0: 0, c1: 9, row: 21.5 },
};

// ===================== 敵データ（通常10種＋レア2種） =====================
// kind はバトル絵のキー: assets/enemy/<kind>_battle.png を置くと自動で差し替わる
// （無い間は紫のもののけ描画）。exp/gold は [下限, 上限]。ハードのHP補正は戦闘側で掛かる。
// 権利面: すべて創作名（実在キャラ・商標は使わない）。モチーフは長久手の史跡・伝承。
const ENEMY_DEFS = {
  // --- 全域（序盤〜） ---
  hagure:    { name: '落武者の もののけ', kind: 'enemy', hp: 22, atkLo: 3, atkHi: 6, exp: [5, 8], gold: [80, 150], lore: '戦で 散った兵の 無念が 形に なったもの。塚に 心を 残している', },
  monomi:    { name: '物見の もののけ', kind: 'monomi', hp: 16, atkLo: 2, atkHi: 5, exp: [4, 6], gold: [60, 100],
               atkLabel: '遠眼鏡なげつけ', lore: '偵察兵の 霊。遠眼鏡を いまも 手放せない', },
  yako:      { name: '夜行の もののけ', kind: 'yako', hp: 36, atkLo: 6, atkHi: 10, exp: [16, 22], gold: [180, 260],
               atkLabel: '提灯の 鬼火', miyaLv: 2, lore: '夜の 行列から はぐれた 武者。提灯の 火は 魂そのもの', },
  yako_kage: { name: '夜行の 影', kind: 'yako', hp: 28, atkLo: 5, atkHi: 8, exp: [12, 16], gold: [120, 180],
               atkLabel: '影のびの 一撃', miyaLv: 2, lore: '夜行の もののけの 影が 実体を 持ったもの', },
  // --- ゾーンA: 古戦場公園（陣火・血の池伝承） ---
  onibi:     { name: '鬼火の子', kind: 'onibi', hp: 14, atkLo: 2, atkHi: 4, exp: [3, 5], gold: [50, 90],
               atkLabel: '火の粉とばし', lore: '陣火の 残り火の 精。いたずら好きだが 悪気は ない', },
  chigaeru:  { name: '血の池がえる', kind: 'chigaeru', hp: 20, atkLo: 3, atkHi: 6, exp: [5, 8], gold: [70, 120],
               atkLabel: 'のしかかり体当たり', lore: '武具を 洗った 池の ぬし。赤いのは 血ではなく 錆の色', },
  // --- ゾーンB: 杁ヶ池・御旗山 ---
  mizuchi:   { name: '杁ヶ池の みずち', kind: 'mizuchi', hp: 26, atkLo: 4, atkHi: 7, exp: [8, 12], gold: [90, 150],
               atkLabel: '水しぶき', lore: '杁ヶ池の 若い 水霊。池の 水位を 守っている', },
  hatahira:  { name: '旗指しひらり', kind: 'hatahira', hp: 24, atkLo: 4, atkHi: 7, exp: [8, 12], gold: [90, 150],
               atkLabel: '旗の目くらまし', lore: '戦場に 忘れられた 旗指物の 付喪神。風が 友だち', },
  // --- ゾーンC: 岩作（茶会・戦場の忘れ物） ---
  chagama:   { name: '茶がまだぬき', kind: 'chagama', hp: 30, atkLo: 5, atkHi: 8, exp: [10, 15], gold: [110, 170],
               atkLabel: '熱い湯気ふき', lore: '茶釜に 化けそこねた 狸。湯加減には 自信がある', },
  sabiyari:  { name: '錆槍の 付喪神', kind: 'sabiyari', hp: 34, atkLo: 6, atkHi: 10, exp: [13, 18], gold: [120, 180],
               atkLabel: '錆の槍ぶすま', lore: '置き去りに された 槍の 付喪神。手入れされた 日々を 探している', },
  // --- 東エリア: 里山 ---
  tagakashi: { name: '田がかし武者', kind: 'tagakashi', hp: 38, atkLo: 7, atkHi: 11, exp: [15, 21], gold: [130, 200],
               atkLabel: '竹竿ぶんまわし', miyaLv: 2, lore: '田を 守る 誓いを 立てた 落武者の 魂。夜だけ 動く', },
  // --- 岩崎城（既存の強敵・絵は落武者/物見と共通） ---
  iw_ochi:   { name: '岩崎の 落武者', kind: 'enemy', hp: 30, atkLo: 7, atkHi: 11, exp: [22, 30], gold: [130, 190], miyaLv: 2, lore: '岩崎城の 戦いで 散った 兵。城への 忠義が いまも 残る', },
  iw_monomi: { name: '岩崎の 物見', kind: 'monomi', hp: 24, atkLo: 6, atkHi: 9, exp: [16, 22], gold: [90, 140],
               atkLabel: '遠眼鏡なげつけ', miyaLv: 2, lore: '岩崎城の 物見櫓を 守っていた 兵の 霊', },
  // --- レア敵（全域・低確率） ---
  koban:     { name: 'こばん狐', kind: 'koban', hp: 18, atkLo: 1, atkHi: 3, exp: [6, 10], gold: [800, 1500],
               atkLabel: 'すばしっこい体当たり',
               appearMsg: 'きらりと 光る こばん狐が あらわれた！ 大金の 気配……！', miyaLv: 3, lore: '小判を 集める 金運の 狐。倒した者に 福を 分ける', },
  kabuto:    { name: '黄金の 兜がね', kind: 'kabuto', hp: 46, atkLo: 2, atkHi: 4, exp: [70, 100], gold: [100, 200],
               atkLabel: '角の一突き',
               appearMsg: '黄金に かがやく 兜がねが あらわれた！ 経験の 大チャンス！', miyaLv: 3, lore: '名将の 兜が 甲虫に なった 付喪神。経験の かたまり', },
};

// ゾーン別の出現テーブル（w=重み, mate=お供が付く敵, mateW=お供の確率・既定0.3）
// レア敵はテーブルの前に共通で抽選される（兜がね3%・こばん狐5%）
const ENCOUNTER_TABLES = {
  field:   [{ id: 'hagure', w: 70, mate: 'monomi' }, { id: 'onibi', w: 30 }],
  zoneA:   [{ id: 'onibi', w: 40 }, { id: 'chigaeru', w: 35 }, { id: 'hagure', w: 25, mate: 'monomi' }],
  zoneB:   [{ id: 'mizuchi', w: 45 }, { id: 'hatahira', w: 35 }, { id: 'monomi', w: 20 }],
  zoneC:   [{ id: 'sabiyari', w: 40 }, { id: 'chagama', w: 40 }, { id: 'hagure', w: 20, mate: 'monomi' }],
  zoneD:   [{ id: 'hatahira', w: 45 }, { id: 'chagama', w: 30 }, { id: 'monomi', w: 25 }],
  zoneF:   [{ id: 'sabiyari', w: 45 }, { id: 'tagakashi', w: 30 }, { id: 'onibi', w: 25 }],
  zoneG:   [{ id: 'tagakashi', w: 50 }, { id: 'chigaeru', w: 25 }, { id: 'mizuchi', w: 25 }],
  iwasaki: [{ id: 'iw_ochi', w: 55, mate: 'iw_monomi', mateW: 0.6 }, { id: 'tagakashi', w: 25 }, { id: 'sabiyari', w: 20 }],
};

// ===================== モブNPC（街の人・ストーリー連動） =====================
// spots のキーはフェーズ: quest=取材クエスト中(街解放〜), night=ラスボス前夜(stageP3=9),
// post=クリア後。フェーズにエントリが無いモブはその時期は登場しない（人数・位置が変わる）。
// 会話キーは dialogue.js の mob_<id>_<フェーズ>（無ければ _quest にフォールバック）。
const MOB_DEFS = [
  // --- ゾーンA: 古戦場公園周辺 ---
  { id: 'mob_sanpo', kind: 'civ3', map: 'zoneA',
    spots: { quest: { col: 26, row: 21 }, post: { col: 26, row: 21 } } },
  { id: 'mob_jog', kind: 'civ5', map: 'zoneA',
    spots: { quest: { col: 10, row: 18 }, night: { col: 10, row: 18 }, post: { col: 10, row: 18 } } },
  { id: 'mob_kanko', kind: 'civ2', map: 'zoneA',
    spots: { quest: { col: 31, row: 19 }, post: { col: 26, row: 19 } } },
  { id: 'mob_guide', kind: 'civ6', map: 'zoneA',
    spots: { quest: { col: 24, row: 20 }, post: { col: 24, row: 20 } } },
  { id: 'mob_keibi', kind: 'civ6', map: 'zoneA',
    spots: { night: { col: 31, row: 11 } } },
  { id: 'mob_yatai', kind: 'civ8', map: 'zoneA',
    spots: { post: { col: 23, row: 20 } } },
  // --- ゾーンB: 杁ヶ池・御旗山・住宅地 ---
  { id: 'mob_inu', kind: 'civ1', map: 'zoneB',
    spots: { quest: { col: 7, row: 12 }, post: { col: 7, row: 12 } } },
  { id: 'mob_hiker', kind: 'civ5', map: 'zoneB',
    spots: { quest: { col: 30, row: 9 }, post: { col: 30, row: 9 } } },
  { id: 'mob_shufu', kind: 'civ3', map: 'zoneB',
    spots: { quest: { col: 8, row: 23 }, post: { col: 8, row: 23 } } },
  // --- ゾーンC: 岩作 ---
  { id: 'mob_nofu', kind: 'civ3', map: 'zoneC',
    spots: { quest: { col: 8, row: 20 }, post: { col: 8, row: 20 } } },
  { id: 'mob_shokuin', kind: 'civ6', map: 'zoneC',
    spots: { quest: { col: 33, row: 14 }, night: { col: 33, row: 14 }, post: { col: 33, row: 14 } } },
  { id: 'mob_gyoretsu', kind: 'civ7', map: 'zoneC',
    spots: { quest: { col: 21, row: 21 }, night: { col: 21, row: 21 }, post: { col: 21, row: 21 } } },
  // --- ゾーンD: 文化の家・図書館 ---
  { id: 'mob_gakki', kind: 'civ7', map: 'zoneD',
    spots: { quest: { col: 22, row: 14 }, post: { col: 22, row: 14 } } },
  { id: 'mob_ehon', kind: 'civ4', map: 'zoneD',
    spots: { quest: { col: 33, row: 22 }, post: { col: 33, row: 22 } } },
  // --- ゾーンF: 芸大通 ---
  { id: 'mob_geidaisei', kind: 'civ7', map: 'zoneF',
    spots: { quest: { col: 29, row: 12 }, post: { col: 29, row: 12 } } },
  { id: 'mob_kuruma', kind: 'civ1', map: 'zoneF',
    spots: { quest: { col: 12, row: 19 }, post: { col: 12, row: 19 } } },
  // --- ゾーンG: 公園西 ---
  { id: 'mob_kaimono', kind: 'civ2', map: 'zoneG',
    spots: { quest: { col: 12, row: 20 }, post: { col: 12, row: 20 } } },
  { id: 'mob_yamakid', kind: 'civ4', map: 'zoneG',
    spots: { quest: { col: 29, row: 10 }, post: { col: 29, row: 10 } } },
];
